version: '3.9'
services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
  prisma-sqlite-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-sqlite-api
    depends_on:
      - sqlite3
    ports:
      - '3000:3000'
    restart: always

volumes:
  dbdata:
